packages:
  - "apps/*"
  - "packages/*"
verifyDepsBeforeRun: false
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  esbuild: true
  prisma: true
  spawn-sync: true
  unrs-resolver: true
  youtube-dl-exec: true
